### ISSUE TITLE
Twitter search scrapes fail with `non-200 status code (404)`

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#760]
Since sometime in the past hour or so, all scrapes based on Twitter's search (i.e. `twitter-search`, `twitter-user`, `twitter-hashtag`, `twitter-cashtag`, and `twitter-list-posts`) appear to fail with this kind of error:

```
2023-03-14 00:23:41.196  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=query&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: non-200 status code (404)
2023-03-14 00:23:41.196  CRITICAL  snscrape.base  4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=query&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
2023-03-14 00:23:41.196  CRITICAL  snscrape.base  Errors: non-200 status code (404), non-200 status code (404), non-200 status code (404), non-200 status code (404)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=query&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
```

**Comment by gityousseff** [comment]
i have the same error since hour...

**Comment by raymondispresent** [comment]
Encountering the same error

**Comment by bigishdata** [comment]
Same error here! Been using snscrape for two weeks flawlessly, did you guys have had this type of issues before? awesome tool btw!

**Comment by raymondispresent** [comment]
> Same error here! Been using snscrape for two weeks flawlessly, did you guys have had this type of issues before? awesome tool btw!

First time it's been happening, I think it's on Twitter's side, I'll be checking Twint and any other scrapers to confirm

**Comment by JustAnotherArchivist** [comment]
'Me too!!!' comments are not useful. If you have nothing to contribute to the discussion, please refrain from participating.

Yes, it's a change on Twitter's side, and there's currently no known workaround.

**Comment by alexanderolvera** [comment]
Looks like this could be related to guest user authentication.
Running a failed endpoint with a Bearer token and a guest-token I pulled from twitters website works fine.

**Comment by AlekseiShkurin** [comment]
What is known so far? Is it specifically the guest user authentication issue? I remember when it was down a couple of months ago that seemed to be the issue too

**Comment by doveppp** [comment]
Is there a temporary workaround?

**Comment by alexanderolvera** [comment]
Found a potential
Might be a problem with the user-agent. I swapped it for what my browser is using and I am getting good responses again.

**Comment by alexanderolvera** [comment]
Confirmed. Looks like Twitter might have dropped a few versions of chrome? I'll have a PR in just a sec.

**Comment by JustAnotherArchivist** [comment]
Heh, I discovered the same thing at the same time. Yeah, apparently they really hate old Chrome versions now for some reason. Thanks!

**Comment by JustAnotherArchivist** [comment]
Version 0.6.1 with this fix is released.

**Comment by kongge1264** [comment]
> Version 0.6.1 with this fix is released.

I downloaded this version, but the problem is still not solved.

**Comment by JustAnotherArchivist** [comment]
@kongge1264 I have confirmed from several machines on three continents that it works correctly. If you're seeing that error with version 0.6.1, it's probably not the same issue. Many things can potentially cause this, most commonly banned IPs. If you aren't using AWS or bad proxies and it used to work from the same IPs, please file a complete bug report separately.

**Comment by kongge1264** [comment]
> @kongge1264 I have confirmed from several machines on three continents that it works correctly. If you're seeing that error with version 0.6.1, it's probably not the same issue. Many things can potentially cause this, most commonly banned IPs. If you aren't using AWS or bad proxies and it used to work from the same IPs, please file a complete bug report separately.

I have solved it, thank you very much!

**Comment by ShayanHodai** [comment]
snscrape has released an update on 14th of March. version 0.6.1.20230314

1. first update pip: pip install --upgrade pip
2. then update snscrape to the latest version: pip install --upgrade snscrape
3. check the snscrape's version to be 0.6.1.20230314: pip list | grep snscrape
4. start using snscrape again

**Comment by luisvivasg** [comment]
> Version 0.6.1 with this fix is released.

Last week I upgraded and version 0.6.1 and worked. Today I am getting the same error again.

**Comment by David-Makinde** [comment]
> 

How did you achieve this?

**Comment by David-Makinde** [comment]
> snscrape has released an update on 14th of March. version 0.6.1.20230314
> 
> 1. first update pip: pip install --upgrade pip
> 2. then update snscrape to the latest version: pip install --upgrade snscrape
> 3. check the snscrape's version to be 0.6.1.20230314: pip list | grep snscrape
> 4. start using snscrape again

Done these, and still getting the error

**Comment by JustAnotherArchivist** [comment]
If you still get that error with snscrape 0.6.1, it is not the same issue.
